### ISSUE TITLE
How to enable --use_srtm4 option in command?

### ISSUE THREAD

**Issue by jaskiratsingh2000** [Kai-46/SatelliteSfM#1]
@Kai-46 How to enable --use_srtm4 option in command?

On writing this command I am getting the error.

Command written:

```
python3 satellite_sfm.py --input_folder /Users/jaskiratsingh/IIIT-Hyderabad-Research/SatelliteSfM_Input_Images --output_folder /Users/jaskiratsingh/IIIT-Hyderabad-Research/SatelliteSfM_Output_Image --run_sfm [--use_srtm4] [--enable_debug]
```

Error:

```
zsh: no matches found: [--use_srtm4]
```

Can you help me know how can I resolve this?

Thanks!

**Comment by Kai-46** [comment]
Please remove the square bracket (which means optional argument in bash).

**Comment by jaskiratsingh2000** [comment]
Okay, that works for me. Since I am a macOS user so the script stops at installing _gdal into my mac. I have tried every possibility of installing that but have no clue in making the script run. Do you have any idea on how I could install _gdal library into my OS?

**Comment by jaskiratsingh2000** [comment]
@Kai-46 Okay, that works for me. Since I am a macOS user so the script stops at installing _gdal into my mac. I have tried every possibility of installing that but have no clue in making the script run. Do you have any idea on how I could install _gdal library into my OS?

**Comment by Kai-46** [comment]
You probably want to try [conda install -c conda-forge gdal](https://anaconda.org/conda-forge/gdal). But I suggest you try to use this library on a linux machine with Nvidia GPU. I haven't test this package on my Mac

**Comment by jaskiratsingh2000** [comment]
@Kai-46 I don't have a Linux machine installed. I tried the above method and it worked fine but it gave me the error that "gdal" module can't be imported. Do you have any other idea?

**Comment by jaskiratsingh2000** [comment]
@Kai-46 Can you give it a try on MAC as well once?

**Comment by Kai-46** [comment]
Sorry, but I don't have the bandwidth to make this work on Mac at the moment. In the future, I might give it a try.

**Comment by jaskiratsingh2000** [comment]
@Kai-46 I also tried the same thing on the Linux but that gave me the same result. Hence I am not sure how exactly were you able to solve this for the GDAL installation of the library.
