### ISSUE TITLE
ColmapForVisSatPatched

### ISSUE THREAD

**Issue by SBCV** [Kai-46/SatelliteSfM#4]
Hi Kai,

I had some time and implemented [ColmapForVisSat using git patch](https://github.com/SBCV/ColmapForVisSatPatched).  I was able to re-create some satellite reconstructions using the latest Colmap version.

Best regards,
Sebastian

**Comment by Kai-46** [comment]
Wow, that's awesome! I'll take a look at it in the coming days. Thank you, Sebastian!

**Comment by SBCV** [comment]
Btw: As reference for the patch creation, I squashed all your commits into a single commit as can be seen here: https://github.com/SBCV/ColmapForVisSat/commit/840b30ffb2b4ea896245619c8575687ed8743c47
