### ISSUE TITLE
What downstream algorithm adopted to achieve the effect of JAX_166_compressed.mp4  ？

### ISSUE THREAD

**Issue by StriveZs** [Kai-46/SatelliteSfM#8]
Hi Kai,
Thanks for providing this awesome repo !
Recently, we want to use some satellite images to finish remote sensing large-scale city reconstruction. And we find the effect of JAX_166_compressed.mp4 is very meet our need. But we can't find any certainly content of downstream algorithm description you adopted. Is Neus or MVS ? 
Can you give us some helps ? We also want to obtain similar results from you.

**Comment by Kai-46** [comment]
It's SatelliteNeuS: https://github.com/Kai-46/SatelliteNeuS

**Comment by StriveZs** [comment]
> 

Thank you very much, buddy !
